CREATE TABLE IF NOT EXISTS `#__dateupdate` (
    `id` int(10) NOT NULL AUTO_INCREMENT,
    `date` varchar(100) NOT NULL,

    PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1; 
